CREATE TABLE [dbo].[PosterData] (
    [StudentID] INT           NOT NULL,
    [Name]      NVARCHAR (50) NULL,
    [1]         NVARCHAR (50) NULL,
    [2]         NVARCHAR (50) NULL,
    [3]         NVARCHAR (50) NULL,
    [4]         NVARCHAR (50) NULL,
    [5]         NVARCHAR (50) NULL,
    [6]         NVARCHAR (50) NULL,
    [7]         NVARCHAR (50) NULL,
    [8]         NVARCHAR (50) NULL,
    [9]         NVARCHAR (50) NULL,
    [10]        NVARCHAR (50) NULL,
    [11]        NVARCHAR (50) NULL,
    [12]        NVARCHAR (50) NULL,
    [13]        NVARCHAR (50) NULL,
    [14]        NVARCHAR (50) NULL,
    [15]        NVARCHAR (50) NULL,
    [16]        NVARCHAR (50) NULL,
    [17]        NVARCHAR (50) NULL,
    [18]        NVARCHAR (50) NULL,
    [19]        NVARCHAR (50) NULL,
    [20]        NVARCHAR (50) NULL,
    CONSTRAINT [PK_PosterData] PRIMARY KEY CLUSTERED ([StudentID] ASC)
);